### ISSUE TITLE
Client Language Performance Comparison

### ISSUE THREAD

**Issue by ea020** [aws-samples/trading-latency-benchmark#22]
### Describe the feature

First of all, thank you for this article and repository.  It clearly shows the effect of network differences. 

I have a question about the clients. Did you compare the performance of the C++ and Java clients? Do you think can Java be more performant than C++ when you tweak it? Thank you in advance,

(I tried to ask this as a general discussion but that link is not working.)

### Use Case

Client performance compare 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Language

Java

**Comment by SercanKaraoglu** [comment]
Hi, 
The main purpose of this repo was to test network architectures mentioned in the blog by simulating typical high-frequency trading (HFT) behavior, which involves sequential limit and cancel orders.

Regarding your question about Java and C++, I initially wanted to develop a faster client using C++. However, it turned out that my C++ client, which I developed in just two days, wasn't as good as my Java client. I beleive there are a couple of reasons for this:
    C++ is not my main expertise, so there's likely room for optimization.
    To get something working quickly within two days, I had to use a WebSocketpp framework, which means I relied on the quality of that framework's implementation instead of having a full control.

As a result, it became more of a framework comparison (e.g., Netty vs. WebSocketpp) rather than a pure Java vs. C++ comparison. In theory, after the just-in-time compiler kicks in, Java and C++ performance should be quite similar. However, based on my tests, my Java client was way faster due to the reasons mentioned above.
